//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTORITEM
    {
        public int ID { get; set; }
        public Nullable<int> COUNT { get; set; }
        public Nullable<long> LastPurchFee { get; set; }
        public Nullable<long> LastBuyFee { get; set; }
        public Nullable<int> FactorId { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual FACTOR FACTOR { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
