//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTOR()
        {
            this.FACTORITEMS = new HashSet<FACTORITEM>();
        }
    
        public int Id { get; set; }
        public string StartDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> LastBuyFee { get; set; }
        public Nullable<long> LastPurchFee { get; set; }
        public Nullable<bool> PurchType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTORITEM> FACTORITEMS { get; set; }
    }
}
