//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.PRODUCTPRICEs = new HashSet<PRODUCTPRICE>();
            this.TRANSACTIONs = new HashSet<TRANSACTION>();
            this.FACTORITEMS = new HashSet<FACTORITEM>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDiscription { get; set; }
        public byte[] ProductImage { get; set; }
        public Nullable<long> ProductLastFee { get; set; }
        public Nullable<int> ProductLastSuply { get; set; }
        public string ProductStartDate { get; set; }
        public string ProductUpdateDate { get; set; }
        public int UsersId { get; set; }
        public Nullable<byte> ProductActive { get; set; }
        public Nullable<long> ProductLastPurchFee { get; set; }
    
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTPRICE> PRODUCTPRICEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACTION> TRANSACTIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTORITEM> FACTORITEMS { get; set; }
    }
}
