//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
            this.PRODUCTPRICEs = new HashSet<PRODUCTPRICE>();
            this.TRANSACTIONs = new HashSet<TRANSACTION>();
            this.USERSLOGs = new HashSet<USERSLOG>();
            this.Customers = new HashSet<Customer>();
            this.FACTORs = new HashSet<FACTOR>();
        }
    
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string USERFAMILY { get; set; }
        public Nullable<byte> USERAGE { get; set; }
        public Nullable<byte> USERSEX { get; set; }
        public Nullable<byte> USERACTIVE { get; set; }
        public string USERUSERNAME { get; set; }
        public string USERPASSWORD { get; set; }
        public string USERADDRESS { get; set; }
        public string USERSTARTDATE { get; set; }
        public string USERUPDATEDATE { get; set; }
        public string USERNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTPRICE> PRODUCTPRICEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACTION> TRANSACTIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERSLOG> USERSLOGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTOR> FACTORs { get; set; }
    }
}
