//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERSLOG
    {
        public int ID { get; set; }
        public string PCNAME { get; set; }
        public string IPADDRESS { get; set; }
        public string STARTDATE { get; set; }
        public string ENDDATE { get; set; }
        public Nullable<int> USERSID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
