//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CUSTOMERS
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string StartDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string USERNAME { get; set; }
        public string USERFAMILY { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<byte> IsActive { get; set; }
    }
}
