//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PRODUCTS
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDiscription { get; set; }
        public byte[] ProductImage { get; set; }
        public Nullable<long> ProductLastFee { get; set; }
        public Nullable<int> ProductLastSuply { get; set; }
        public string ProductStartDate { get; set; }
        public string ProductUpdateDate { get; set; }
        public int UsersId { get; set; }
        public string USERNAME { get; set; }
        public string USERFAMILY { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<byte> ProductActive { get; set; }
        public Nullable<long> ProductLastPurchFee { get; set; }
    }
}
