//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PRODUCTPRICE
    {
        public int ID { get; set; }
        public Nullable<long> SELLPRICE { get; set; }
        public Nullable<long> BUYPRICE { get; set; }
        public string DISCRIPTION { get; set; }
        public string STARTDATE { get; set; }
        public Nullable<int> USERSID { get; set; }
        public Nullable<int> PRODUCTSID { get; set; }
        public string ProductName { get; set; }
        public string USERNAME { get; set; }
        public string USERFAMILY { get; set; }
        public string FULLNAME { get; set; }
    }
}
