//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_USERS
    {
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string USERFAMILY { get; set; }
        public Nullable<byte> USERAGE { get; set; }
        public Nullable<byte> USERSEX { get; set; }
        public Nullable<byte> USERACTIVE { get; set; }
        public string USERUSERNAME { get; set; }
        public string USERPASSWORD { get; set; }
        public string USERADDRESS { get; set; }
        public string USERSTARTDATE { get; set; }
        public string USERUPDATEDATE { get; set; }
        public string USERNO { get; set; }
        public string ACTIVEFARSI { get; set; }
        public string GENDERFARSI { get; set; }
        public string FULLNAME { get; set; }
    }
}
